# Generated by Django 5.0.1 on 2024-01-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_roomservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomservice',
            name='note',
            field=models.TextField(default='Travis Scott concert'),
            preserve_default=False,
        ),
    ]
