# Generated by Django 5.0.1 on 2024-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomservice',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='roomservice',
            old_name='servicesType',
            new_name='services_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
