# Generated by Django 5.0.1 on 2024-01-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_event_eventtype_alter_roomservice_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventType',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='eventattendees',
            old_name='numberOfDependees',
            new_name='number_of_dependees',
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.guest')),
            ],
        ),
        migrations.CreateModel(
            name='FolioPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('department', models.CharField(max_length=20)),
                ('revenue', models.CharField(max_length=20)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.folio')),
            ],
        ),
        migrations.AddField(
            model_name='folio',
            name='folio_postings',
            field=models.ManyToManyField(related_name='folio_postings', to='hotels.folioposting'),
        ),
        migrations.DeleteModel(
            name='RoomService',
        ),
    ]
