# Generated by Django 5.0.1 on 2024-03-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_event_user_eventattendees_user_folio_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(),
        ),
    ]
