services:
  web:
    container_name: web
    depends_on:
      - db
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER= ${DB_USER}
      - DB_PASSWORD= ${DB_PASSWORD}
      - DB_NAME= ${DB_NAME}
      - DEBUG=True
    command: ["gunicorn", "-c", "gunicorn_config.py", "HotelHub.wsgi"]
    restart: always
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_PORT=5432
      - DB_NAME=postgres
      - DEBUG=True
    command: ["python", "manage.py", "migrate"]
    restart: on-failure
  db:
    image: "postgres:15"
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres